# Generated by Django 3.2.5 on 2021-07-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0002_auto_20210723_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('deactivated', models.BooleanField(default=False)),
                ('registration_authenticated', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        
        migrations.DeleteModel(
            name='Register',
        ),
    ]
