# Generated by Django 3.2.5 on 2021-07-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0003_auto_20210726_1001'),
    ]