# Generated by Django 3.2.5 on 2021-07-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0004_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BALANCE', models.CharField(blank=True, max_length=200, null=True)),
                ('NARRATION', models.CharField(blank=True, max_length=200, null=True)),
                ('TRANSACTION_DATE', models.CharField(blank=True, max_length=200, null=True)),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
                ('transactionAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('transactionPrimaryCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('transactionType', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),

    ]
