# Generated by Django 3.2.5 on 2021-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0005_auto_20210728_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsontab',
            name='transactionSecondaryCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
